Node yaml config
vitekkor/mintKV pull request #18
Opened 2024-04-16 09:41 UTC by axothy

#7

2024-04-16 10:04 UTC, vitekkor requested changes

2024-04-16 10:04 UTC, vitekkor commented on database/src/main/java/com/mint/db/config/ConfigParser.java
> +    private static final String NODE_CONFIG_PATH_DEFAULT = "database/src/main/resources/node-config.yaml";
Это будет работать только при запуске из идеи, при сборке jar у нас всё сломается

2024-04-16 10:04 UTC, vitekkor commented on database/src/main/java/com/mint/db/config/ConfigParser.java
> +        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
Выглядит как-то ненадёжно. Может какую-нибудь библиотеку использовать лучше?

2024-04-16 10:05 UTC, axothy commented on database/src/main/java/com/mint/db/config/ConfigParser.java
> +        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
Можно SnakeYaml

2024-04-16 10:28 UTC, axothy commented on database/src/main/java/com/mint/db/config/ConfigParser.java
> +        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
Оказалось что мой код был надежнее чем библиотека

2024-04-18 11:35 UTC, axothy commented
@vitekkor Чуть изменил формат yaml файла и свичнулся на библиотеку snakeYaml. Подойдет такой формат конфига?

2024-04-18 11:47 UTC, vitekkor commented on database/src/main/java/com/mint/db/config/ConfigParser.java
> +                .getResourceAsStream(
Вот это надо бы проверить - если у тебя NODE_CONFIG_PATH_DEFAULT будет, то там всё ок, из ресурсов достанем yaml. А вот если у тебя configPath будет не null и равен например /etc/config/application.yml, то мне кажется, что getResourceAsStream сломается. Но это надо проверить

2024-04-18 11:50 UTC, axothy commented on database/src/main/java/com/mint/db/config/ConfigParser.java
> +                .getResourceAsStream(
Ну как ты говорил, это может сломаться при сборке JAR? по идее не сломается если `/etc/config/application.yml` будет лежать в ресурсах тоже

2024-04-20 18:17 UTC, vitekkor commented on database/src/main/java/com/mint/db/config/ConfigParser.java
> +                .getResourceAsStream(
Не, /etc/config/application.yml лежит вне jar файла

Поэтому и надо проверить

2024-04-21 09:35 UTC, axothy commented
@vitekkor Проверил, работает теперь и для конфига из ресурсов, и для внешнего конфига

2024-04-21 11:12 UTC, vitekkor approved these changes

2024-04-21 11:12 UTC, merged