closes #38 and implements log rollback without data rollback
vitekkor/mintKV pull request #42
Opened 2024-05-30 15:13 UTC by Nikpro200125

2024-05-30 16:40 UTC, vitekkor requested changes

2024-05-30 16:40 UTC, vitekkor commented on database/src/main/java/com/mint/db/replication/impl/ReplicatedLogManagerImpl.java
> +            MemorySegment ms = fileChannel.map(FileChannel.MapMode.READ_ONLY, 0, Files.size(indexFile), Arena.ofAuto());
А постоянно хранить mapped memorySegment мы не можем из-за изменяющегося размера файла?
А что если `MemorySegment::reinterpret(long newSize)` попробовать использовать?

2024-05-30 16:40 UTC, vitekkor commented on database/src/main/java/com/mint/db/replication/impl/ReplicatedLogManagerImpl.java
> +    private long calculateLogEntrySize(LogEntry<MemorySegment> logEntry) {
Мб static?

2024-05-30 16:40 UTC, vitekkor commented on database/src/main/java/com/mint/db/replication/impl/ReplicatedLogManagerImpl.java
> +    private LogId lastLogId;
```suggestion
    private LogId lastLogId = new LogId(0, 0);
```

Возможно это пофиксит проблему с тестами

2024-05-30 16:40 UTC, vitekkor commented on database/src/main/java/com/mint/db/replication/impl/ReplicatedLogManagerImpl.java
> +        List<LogEntry<MemorySegment>> logEntries = new ArrayList<>();
```suggestion
        List<LogEntry<MemorySegment>> logEntries = new ArrayList<>(amount);
```

2024-05-30 16:40 UTC, vitekkor commented on database/src/main/java/com/mint/db/replication/ReplicatedLogManager.java
> +    List<LogEntry<D>> readLog(long fromIndex, long toIndex);
Старый метод, который читает по одному индексу, тоже нужно оставить

Если я правильно понял, то можно вот так сделать:

```java

    default LogEntry<D> readLog(long index) {
        java.util.List<LogEntry<D>> logEntries = readLog(index, index + 1);
        return !logEntries.isEmpty() ? logEntries.getFirst() : null;
    }
```

2024-05-30 17:12 UTC, Nikpro200125 commented on database/src/main/java/com/mint/db/replication/impl/ReplicatedLogManagerImpl.java
> +    private LogId lastLogId;
да, пофиксило

2024-06-02 14:47 UTC, vitekkor reviewed
Всё ок, ждём фиксы для BaseEntry из #28

2024-06-05 13:15 UTC, vitekkor approved these changes

2024-06-05 13:16 UTC, merged