changed BaseEntry, implemented DaoStateMachine::apply method
vitekkor/mintKV pull request #44
Opened 2024-05-30 16:24 UTC by axothy

Как поступить с ошибками которые возникли при изменении класса BaseEntry?

2024-05-30 18:45 UTC, vitekkor requested changes
\+ codestyle пофиксить

2024-05-30 18:45 UTC, vitekkor commented on database/src/main/java/com/mint/db/dao/impl/BaseEntry.java
>      public static BaseEntry<MemorySegment> valueOf(Raft.LogEntry entry) {
Этот метод надо доработать

2024-05-30 18:45 UTC, vitekkor commented on database/src/main/java/com/mint/db/dao/impl/StringDaoWrapper.java
> +        return new BaseEntry<>(toString(entry.key()), toString(entry.committedValue()));
Тут надо использовать другой конструктор с `uncommittedValue` и `uncommittedValueIsNotNull`

2024-05-30 18:45 UTC, vitekkor commented on database/src/main/java/com/mint/db/dao/impl/StringDaoWrapper.java
> +                = new BaseEntry<>(toMemorySegment(entry.key()), toMemorySegment(entry.committedValue()));
Тут тоже надо использовать другой конструктор с `uncommittedValue` и `uncommittedValueIsNotNull`

2024-05-30 18:45 UTC, vitekkor commented on database/src/main/java/com/mint/db/raft/DaoStateMachine.java
> +            case OperationType.PUT -> {
Мб вынести логику для операции PUT и DELETE в один метод/под один case? У них по сути отличия только в том, что мы записываем в качестве committedValue.

`new BaseEntry<>(key, value, null, false)` -  PUT

`new BaseEntry<>(key, null, null, false)` -  DELETE

2024-05-30 18:45 UTC, vitekkor commented on database/src/main/java/com/mint/db/raft/StateMachine.java
> +    CommandResult apply(LogEntry<MemorySegment> logEntry, boolean commited);
Тут ошибка - нужно оставить в интерфейсе `LogEntry<D>`

2024-06-02 20:07 UTC, axothy commented on database/src/main/java/com/mint/db/dao/impl/BaseEntry.java
>      public static BaseEntry<MemorySegment> valueOf(Raft.LogEntry entry) {
какой метод? valueOf? он не компилировался изначально

2024-06-02 20:11 UTC, axothy commented on database/src/main/java/com/mint/db/dao/impl/StringDaoWrapper.java
> +        return new BaseEntry<>(toString(entry.key()), toString(entry.committedValue()));
Ок

2024-06-02 20:14 UTC, axothy commented on database/src/main/java/com/mint/db/dao/impl/BaseEntry.java
>      public static BaseEntry<MemorySegment> valueOf(Raft.LogEntry entry) {
странный какой-то метод, почему там берется MemorySegment, конвертируется в строку, а потом снова в MemorySegment?

2024-06-02 20:17 UTC, axothy commented on database/src/main/java/com/mint/db/dao/impl/BaseEntry.java
>      public static BaseEntry<MemorySegment> valueOf(Raft.LogEntry entry) {
Вот так мб?
```
    public static BaseEntry<MemorySegment> valueOf(LogEntry<MemorySegment> logEntry) {
        return new BaseEntry<>(
                logEntry.entry().key(),
                logEntry.entry().committedValue(),
                logEntry.entry().uncommittedValue(),
                logEntry.entry().uncommittedValue() != null
        );
    }
```

2024-06-02 20:20 UTC, axothy commented on database/src/main/java/com/mint/db/dao/impl/StringDaoWrapper.java
> +                = new BaseEntry<>(toMemorySegment(entry.key()), toMemorySegment(entry.committedValue()));
Ок

2024-06-02 20:33 UTC, axothy commented on database/src/main/java/com/mint/db/raft/StateMachine.java
> +    CommandResult apply(LogEntry<MemorySegment> logEntry, boolean commited);
+

2024-06-02 20:33 UTC, axothy commented on database/src/main/java/com/mint/db/raft/StateMachine.java
> +    CommandResult apply(LogEntry<MemorySegment> logEntry, boolean commited);
+

2024-06-02 20:51 UTC, axothy commented
@vitekkor я исправил, проверь плиз правильно ли теперь

2024-06-03 09:35 UTC, vitekkor requested changes

2024-06-03 09:35 UTC, vitekkor commented on database/src/main/java/com/mint/db/dao/impl/BaseEntry.java
> +public record BaseEntry<D>(D key, D committedValue, D uncommittedValue, boolean uncommittedValueIsNotNull) implements Entry<D> {
@axothy Надо поправить

2024-06-03 09:35 UTC, vitekkor commented on database/src/main/java/com/mint/db/dao/impl/StringDaoWrapper.java
> +                entry.uncommittedValue() != null
Вместо этого давай в интерфейс entry добавим метод `boolean uncommittedValueIsNotNull`.

2024-06-03 09:35 UTC, vitekkor commented on database/src/main/java/com/mint/db/dao/impl/StringDaoWrapper.java
> +                entry.uncommittedValue() != null
Тогда тут тоже надо будет `entry.uncommittedValue()` использовать

2024-06-03 09:35 UTC, vitekkor commented on database/src/main/java/com/mint/db/dao/impl/StringDaoWrapper.java
> +                        oldEntry.uncommittedValue() != null
Я бы предложил мб вынести в отдельный метод преобразование Entry<MemorySegment>  в BaseEntry<String> в StringDaoWrapper

2024-06-03 09:35 UTC, vitekkor commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +        for (LogEntry entry : request.getEntriesList()) {
Верни назад, тут всё правильно было. Чтобы красным в идее не подсвечивало выполни задачу gradle 
`./gradlew database:generateProto`

2024-06-03 09:35 UTC, vitekkor commented on database/src/main/java/com/mint/db/replication/model/impl/BaseLogEntry.java
> +    public static BaseLogEntry<MemorySegment> valueOf(LogEntry<MemorySegment> logEntry) {
Надо назад вернуть изменения в этом файле

2024-06-03 09:35 UTC, vitekkor commented on database/src/main/java/com/mint/db/dao/impl/BaseEntry.java
>      public static BaseEntry<MemorySegment> valueOf(Raft.LogEntry entry) {
Нет, не так.
```java
    public static BaseEntry<MemorySegment> valueOf(Raft.LogEntry entry) {
        return new BaseEntry<>(
                StringDaoWrapper.toMemorySegment(entry.getKey().toStringUtf8()),
                StringDaoWrapper.toMemorySegment(entry.getValue().toStringUtf8()),
                null,
                false
        );
    }
```

2024-06-03 09:36 UTC, vitekkor commented
@axothy Сделай либо rebase на master, либо вмерджи его к себе в ветку и исправь конфликты

2024-06-03 10:49 UTC, axothy commented
> @axothy Сделай либо rebase на master, либо вмерджи его к себе в ветку и исправь конфликты

Сейчас ребейзнусь

2024-06-03 10:56 UTC, axothy commented
Пофиксил конфликт

2024-06-04 10:52 UTC, axothy commented
@vitekkor тесты валятся
wrong entry at index 0 from 3 ==> expected: <BaseEntry{key=, committedValue=, uncommittedValue=null, uncommittedValueIsNotNull=false}> but was: <BaseEntry{key=, committedValue=, uncommittedValue=, uncommittedValueIsNotNull=true}>

посмотри это тесты надо переписать или это я не правильно закоммитил энтрю?

2024-06-04 11:18 UTC, vitekkor approved these changes

2024-06-04 11:20 UTC, merged