onClientCommand and onClientCommandResult
vitekkor/mintKV pull request #45
Opened 2024-05-30 20:38 UTC by goshadalbeev

2024-05-30 21:40 UTC, vitekkor requested changes

2024-05-30 21:40 UTC, vitekkor commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +        if (leaderId == nodeId) {
switch-case можно вместо if-else-if

2024-05-30 21:40 UTC, vitekkor commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +            long[] nextIndex = new long[config.getCluster().size()];
Это нужно вынести в поле класса

См. https://github.com/vitekkor/mintKV/pull/43/files#diff-df7eea77989050f1f48787e440207084e3a87222179ea18b1d1ebfbba5975c57R50

2024-05-30 21:40 UTC, vitekkor commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +                                        ? Raft.Operation.PUT : Raft.Operation.GET)
А как же Raft.Operation.DELETE? Если entry.value() == null и , то по сути command instanceof InsertCommand, то это DELETE операция

2024-05-30 21:40 UTC, vitekkor commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +                replicatedLogManager.setCommitIndex(logEntry.logId().index());
Это лишнее здесь. В Raft мы сначала делаем append к нашему логу, а коммитим только после достижения кворума

2024-05-30 21:40 UTC, vitekkor commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +            replicatedLogManager.writePersistentState(new PersistentState(commandResult.term()));
```suggestion
            replicatedLogManager.writePersistentState(new PersistentState(commandResult.term()));
            this.leaderId = leaderId;
```

2024-06-04 18:08 UTC, goshadalbeev commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +        if (leaderId == nodeId) {
давай оставим так как есть

2024-06-04 18:08 UTC, goshadalbeev commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +                                        ? Raft.Operation.PUT : Raft.Operation.GET)
добавил

2024-06-04 18:09 UTC, goshadalbeev commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +                replicatedLogManager.setCommitIndex(logEntry.logId().index());
убрал replicatedLogManager.setCommitIndex(logEntry.logId().index());

2024-06-04 18:09 UTC, goshadalbeev commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +            replicatedLogManager.writePersistentState(new PersistentState(commandResult.term()));
добавил this.leaderId = leaderId;

2024-06-05 22:20 UTC, goshadalbeev commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +            long[] nextIndex = new long[config.getCluster().size()];
вынес

2024-06-06 13:41 UTC, vitekkor approved these changes

2024-06-06 13:42 UTC, merged