onAppendEntryResult implementation
vitekkor/mintKV pull request #53
Opened 2024-06-08 13:31 UTC by axothy

#37 

Требуется консультация и помощь по некоторым шагам в алгоритме (шаги по которым непонятно - в методах указаны как //TODO)

2024-06-08 16:46 UTC, vitekkor requested changes

2024-06-08 16:46 UTC, vitekkor commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +        //TODO update indexes - немного не понял как это сделать
```java
            nextIndex[srcId - 1] = messageLastIndex + 1
            matchIndex[srcId - 1] = messageLastIndex
```

2024-06-08 16:46 UTC, vitekkor commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +                leaderId = -1;
Это лишнее

2024-06-08 16:46 UTC, vitekkor commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +            startTimeout(Timeout.ELECTION_TIMEOUT);
После startTimeout должен быть return из этого if'а

2024-06-08 16:46 UTC, vitekkor commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +        Entry prevEntry = replicatedLogManager.readLog(nextIndex[srcId - 1] - 1).entry();
`nextIndex[srcId - 1] - 1` может быть отрицательным. При отрицательном значении `nextIndex[srcId - 1] - 1` нужно делать `replicatedLogManager.readLog(0)`.

Можно сделать например так:
```java
long prevLogIndex = Math.max(nextIndex[srcId - 1] - 1, 0);
Entry prevEntry = replicatedLogManager.readLog(prevLogIndex).entry();
logId prevLogId = prevEntry != null ? prevEntry.logId() : START_LOG_ID
```

`START_LOG_ID` завести константой в виде: `START_LOG_ID = new LogId(0, 0)`

2024-06-08 16:46 UTC, vitekkor commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +        //TODO требуется помощь с шагом: Формируется и отправляется RPC-запрос
Ну берёшь `Raft.AppendEntriesRequest.newBuilder()` и дальше составляешь запрос.

term - `replicatedLogManager().readPersistentState().currentTerm()`
setPrevLogIndex - в комментарии выше `prevLogId.index()`
setPrevLogTerm - в комментарии выше `prevLogId.term()`
entry - entry выше по коду у тебя  `Entry entry = replicatedLogManager.readLog(nextIndex[srcId - 1]).entry();` 
leaderCommit - `replicatedLogManager().commitIndex()`
leaderId - `nodeId`

ну и в конце концов

`internalGrpcActor.sendAppendEntriesRequest(srcId, appendEntriesRequest, this::onAppendEntryResult);`

2024-06-08 16:46 UTC, vitekkor commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +        if (leaderId == nodeId) {
Не, не так. Убери условие совсем

2024-06-08 16:46 UTC, vitekkor commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +            for (long index = replicatedLogManager.commitIndex() + 1; index < messageLastIndex; index++) {
Вот тут `index <= messageLastIndex`

2024-06-08 16:46 UTC, vitekkor commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +                        && replicatedLogManager.readLog(index).logId().term() == state.currentTerm()) {
У тебя тут readLog может null вернуть. Надо бы захендлить это дело. Предлагаю вынести чтение лога в отдельную переменную, а потом сделать что-то типа такого:
`boolean isLogTermEqualToCurrentTerm = logEntry != null ? logEntry.logId().term() == state.currentTerm() : false`

2024-06-08 16:46 UTC, vitekkor commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +                Collection<CommandResult> leaderResults = new ArrayList<>();
Перенеси это под условие ниже

2024-06-08 16:46 UTC, vitekkor commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +                    for (long i = replicatedLogManager.commitIndex() + 1; i < index; i++) {
`i <= index`

2024-06-08 16:46 UTC, vitekkor commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +                                StringDaoWrapper.toString(replicatedLogManager.readLog(index).entry().key()),
`(replicatedLogManager.readLog(index)` вынеси в переменную logEntry. Потом её используй и в строке

`&& replicatedLogManager.readLog(index).logId().term() == state.currentTerm()`

Чтобы не читать по 25 раз.

2024-06-08 16:46 UTC, vitekkor commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +                        }
else ветка:
```
else if (leaderId == nodeId && logEntry.logId().term() == state.currentTerm) {
    externalGrpcActorInterface.onClientCommandResult(// TODO parameters);
```

2024-06-08 16:46 UTC, vitekkor commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +                                /*fixme what a parameter must to be here (long processId) ???*/ 0L,
пу пу пу, похоже надо в logEntry сохранять ещё и pid. Давай пока так - добавь в интерфейс функцию `    int processId();` и пусть в baseEntry она возвращает всегда 0. Я потом доделаю так, чтобы возвращалось норм значение

2024-06-08 16:46 UTC, vitekkor commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +                    //fixme что в параметры кидать ? а точнее в параметр command,
Туда надо тогда короче хранить не список, а мапу Command - CommandResult. И в этой строке `leaderResults.add(commandResult);` делать `leaderResults.put(command, commandResult);`.

А ещё лучше наверное завести класс Pair:

```
public record Pair<A, B>(A first, B second) {
}
```

и в лист добавлять пару: `leaderResults.add(new Pair<>(command, commandResult));`

2024-06-08 16:46 UTC, vitekkor commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +                //TODO update commit index - пока не понял как это сделать
`replicatedLogManager().setCommitIndex();`

2024-06-09 12:23 UTC, axothy commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +        //TODO update indexes - немного не понял как это сделать
Ок

2024-06-09 12:23 UTC, axothy commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +                leaderId = -1;
synchronized блок? или leaderId = -1 (так было в описании задачи)

2024-06-09 12:31 UTC, vitekkor commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +                leaderId = -1;
`leaderId = -1`. Чуть чуть требования поменялись)

2024-06-09 12:42 UTC, axothy commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +        if (leaderId == nodeId) {
Ок

2024-06-09 12:43 UTC, axothy commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +            for (long index = replicatedLogManager.commitIndex() + 1; index < messageLastIndex; index++) {
Поменял на <=

2024-06-09 12:46 UTC, axothy commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +        //TODO требуется помощь с шагом: Формируется и отправляется RPC-запрос
составил запрос

2024-06-09 12:51 UTC, axothy commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +                        && replicatedLogManager.readLog(index).logId().term() == state.currentTerm()) {
Ок, идея предложила упростить `boolean isLogTermEqualToCurrentTerm = logEntry != null && logEntry.logId().term() == state.currentTerm();`

2024-06-09 12:52 UTC, axothy commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +                Collection<CommandResult> leaderResults = new ArrayList<>();
Ок

2024-06-09 12:52 UTC, axothy commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +                    for (long i = replicatedLogManager.commitIndex() + 1; i < index; i++) {
Ок

2024-06-09 12:53 UTC, axothy commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +                                StringDaoWrapper.toString(replicatedLogManager.readLog(index).entry().key()),
Ок

2024-06-09 12:59 UTC, axothy commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +                        }
Добавила

2024-06-09 12:59 UTC, axothy commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +                                /*fixme what a parameter must to be here (long processId) ???*/ 0L,
Ок, сделаю

2024-06-09 13:38 UTC, axothy commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +                    //fixme что в параметры кидать ? а точнее в параметр command,
Ok

2024-06-09 13:51 UTC, axothy commented
@vitekkor Исправил замечания

2024-06-09 14:34 UTC, vitekkor requested changes

2024-06-09 14:34 UTC, vitekkor commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +            LogEntry logEntry = replicatedLogManager.readLog(index);
```suggestion
            LogEntry<MemorySegment> logEntry = replicatedLogManager.readLog(index);
```

2024-06-09 14:34 UTC, vitekkor commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +                    );
```suggestion
                    Command command;
                    if (logEntryMemorySegment.operationType() == OperationType.GET) {
                        command = new GetCommand(
                                logEntryMemorySegment.entry().processId(),
                                StringDaoWrapper.toString(logEntryMemorySegment.entry().key()),
                                DatabaseServiceOuterClass.ReadMode.READ_COMMITTED
                        );
                    } else {
                        command = new InsertCommand(
                                logEntryMemorySegment.entry().processId(),
                                StringDaoWrapper.toString(logEntryMemorySegment.entry().key()),
                                StringDaoWrapper.toString(logEntryMemorySegment.entry().readUncommittedValue()),
                                false
                        );
                    }
```

2024-06-09 14:34 UTC, vitekkor commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +                    } else if (leaderId == nodeId && logEntry.logId().term() == state.currentTerm()) {
```suggestion
                    } else if (leaderId == nodeId && logEntryMemorySegment.logId().term() == state.currentTerm()) {
```

2024-06-09 14:34 UTC, vitekkor commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +        LogEntry logEntry = replicatedLogManager.readLog(nextIndex[srcId - 1]);
```suggestion
        LogEntry<MemorySegment> logEntry = replicatedLogManager.readLog(nextIndex[srcId - 1]);
```

2024-06-09 14:34 UTC, vitekkor commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +        LogEntry prevLogEntry = replicatedLogManager.readLog(prevLogIndex);
```suggestion
        LogEntry<MemorySegment> prevLogEntry = replicatedLogManager.readLog(prevLogIndex);
```

2024-06-09 14:34 UTC, vitekkor commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +        Entry prevEntry = prevLogEntry.entry();
```suggestion
        Entry<MemorySegment> prevEntry = prevLogEntry.entry();
```

2024-06-09 14:34 UTC, vitekkor commented on database/src/main/java/com/mint/db/raft/RaftActor.java
> +}
```suggestion
}

```

2024-06-09 15:09 UTC, vitekkor approved these changes

2024-06-09 15:10 UTC, merged